//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 01:34:13 PM CST 
//


package com.splitsecnd.integration.ima.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationHeader"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qualifiedAddress" type="{http://not.ima.tm.fr/telematic}Address" minOccurs="0"/&gt;
 *         &lt;element name="projectionSystemCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LocationConfidence" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gpsAccuracy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gpsAccuracyUnit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="altitudeUnit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastLocationTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="locations" type="{http://not.ima.tm.fr/telematic}Location" maxOccurs="10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationHeader", propOrder = {
    "qualifiedAddress",
    "projectionSystemCode",
    "locationConfidence",
    "gpsAccuracy",
    "gpsAccuracyUnit",
    "altitudeUnit",
    "lastLocationTimestamp",
    "locations"
})
public class LocationHeader {

    protected Address qualifiedAddress;
    @XmlElement(required = true)
    protected String projectionSystemCode;
    @XmlElement(name = "LocationConfidence", required = true)
    protected String locationConfidence;
    @XmlElement(required = true)
    protected String gpsAccuracy;
    @XmlElement(required = true)
    protected String gpsAccuracyUnit;
    @XmlElement(required = true)
    protected String altitudeUnit;
    @XmlElement(required = true)
    protected String lastLocationTimestamp;
    @XmlElement(required = true)
    protected List<Location> locations;

    /**
     * Gets the value of the qualifiedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getQualifiedAddress() {
        return qualifiedAddress;
    }

    /**
     * Sets the value of the qualifiedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setQualifiedAddress(Address value) {
        this.qualifiedAddress = value;
    }

    /**
     * Gets the value of the projectionSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectionSystemCode() {
        return projectionSystemCode;
    }

    /**
     * Sets the value of the projectionSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectionSystemCode(String value) {
        this.projectionSystemCode = value;
    }

    /**
     * Gets the value of the locationConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationConfidence() {
        return locationConfidence;
    }

    /**
     * Sets the value of the locationConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationConfidence(String value) {
        this.locationConfidence = value;
    }

    /**
     * Gets the value of the gpsAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpsAccuracy() {
        return gpsAccuracy;
    }

    /**
     * Sets the value of the gpsAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpsAccuracy(String value) {
        this.gpsAccuracy = value;
    }

    /**
     * Gets the value of the gpsAccuracyUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpsAccuracyUnit() {
        return gpsAccuracyUnit;
    }

    /**
     * Sets the value of the gpsAccuracyUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpsAccuracyUnit(String value) {
        this.gpsAccuracyUnit = value;
    }

    /**
     * Gets the value of the altitudeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltitudeUnit() {
        return altitudeUnit;
    }

    /**
     * Sets the value of the altitudeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltitudeUnit(String value) {
        this.altitudeUnit = value;
    }

    /**
     * Gets the value of the lastLocationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastLocationTimestamp() {
        return lastLocationTimestamp;
    }

    /**
     * Sets the value of the lastLocationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastLocationTimestamp(String value) {
        this.lastLocationTimestamp = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     * @return
     *     possible object is
     *     {@link List }
     */
    public List<Location> getLocations() {
        if (locations == null) {
            locations = new ArrayList<Location>();
        }
        return this.locations;
    }

}
