//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 01:34:13 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://not.ima.tm.fr/telematic", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.splitsecnd.integration.ima.model;
