//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 01:34:13 PM CST 
//


package com.splitsecnd.integration.ima.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Event Information of a vehicle, usually used for
 *         ecall.
 * 
 * <p>Java class for VehicleAccidentContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleAccidentContext"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://not.ima.tm.fr/telematic}ContextObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rolled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="airbag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="crash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="engine" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="noignition" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="moving" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="frontcrash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="rearcrash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="sidecrash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="passengers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="deccel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="deccelUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="towNeeded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="theftTrackingActivated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="inCarAlarmTriggered" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="serviceProviderAdresse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleAccidentContext", propOrder = {
    "rolled",
    "airbag",
    "crash",
    "engine",
    "noignition",
    "moving",
    "frontcrash",
    "rearcrash",
    "sidecrash",
    "passengers",
    "deccel",
    "deccelUnit",
    "towNeeded",
    "theftTrackingActivated",
    "inCarAlarmTriggered",
    "serviceProviderAdresse"
})
public class VehicleAccidentContext
    extends ContextObject
{

    protected Boolean rolled;
    protected Boolean airbag;
    protected Boolean crash;
    protected Boolean engine;
    protected Boolean noignition;
    protected Boolean moving;
    protected Boolean frontcrash;
    protected Boolean rearcrash;
    protected Boolean sidecrash;
    protected Integer passengers;
    protected Integer deccel;
    protected String deccelUnit;
    protected Boolean towNeeded;
    protected Boolean theftTrackingActivated;
    protected Boolean inCarAlarmTriggered;
    protected String serviceProviderAdresse;

    /**
     * Gets the value of the rolled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRolled() {
        return rolled;
    }

    /**
     * Sets the value of the rolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRolled(Boolean value) {
        this.rolled = value;
    }

    /**
     * Gets the value of the airbag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirbag() {
        return airbag;
    }

    /**
     * Sets the value of the airbag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirbag(Boolean value) {
        this.airbag = value;
    }

    /**
     * Gets the value of the crash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCrash() {
        return crash;
    }

    /**
     * Sets the value of the crash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCrash(Boolean value) {
        this.crash = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEngine(Boolean value) {
        this.engine = value;
    }

    /**
     * Gets the value of the noignition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoignition() {
        return noignition;
    }

    /**
     * Sets the value of the noignition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoignition(Boolean value) {
        this.noignition = value;
    }

    /**
     * Gets the value of the moving property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMoving() {
        return moving;
    }

    /**
     * Sets the value of the moving property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMoving(Boolean value) {
        this.moving = value;
    }

    /**
     * Gets the value of the frontcrash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFrontcrash() {
        return frontcrash;
    }

    /**
     * Sets the value of the frontcrash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFrontcrash(Boolean value) {
        this.frontcrash = value;
    }

    /**
     * Gets the value of the rearcrash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRearcrash() {
        return rearcrash;
    }

    /**
     * Sets the value of the rearcrash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRearcrash(Boolean value) {
        this.rearcrash = value;
    }

    /**
     * Gets the value of the sidecrash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSidecrash() {
        return sidecrash;
    }

    /**
     * Sets the value of the sidecrash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSidecrash(Boolean value) {
        this.sidecrash = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPassengers(Integer value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the deccel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeccel() {
        return deccel;
    }

    /**
     * Sets the value of the deccel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeccel(Integer value) {
        this.deccel = value;
    }

    /**
     * Gets the value of the deccelUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeccelUnit() {
        return deccelUnit;
    }

    /**
     * Sets the value of the deccelUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeccelUnit(String value) {
        this.deccelUnit = value;
    }

    /**
     * Gets the value of the towNeeded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTowNeeded() {
        return towNeeded;
    }

    /**
     * Sets the value of the towNeeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTowNeeded(Boolean value) {
        this.towNeeded = value;
    }

    /**
     * Gets the value of the theftTrackingActivated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTheftTrackingActivated() {
        return theftTrackingActivated;
    }

    /**
     * Sets the value of the theftTrackingActivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTheftTrackingActivated(Boolean value) {
        this.theftTrackingActivated = value;
    }

    /**
     * Gets the value of the inCarAlarmTriggered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInCarAlarmTriggered() {
        return inCarAlarmTriggered;
    }

    /**
     * Sets the value of the inCarAlarmTriggered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInCarAlarmTriggered(Boolean value) {
        this.inCarAlarmTriggered = value;
    }

    /**
     * Gets the value of the serviceProviderAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProviderAdresse() {
        return serviceProviderAdresse;
    }

    /**
     * Sets the value of the serviceProviderAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProviderAdresse(String value) {
        this.serviceProviderAdresse = value;
    }

}
